CLASS zcl_rap_claim_hdr DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zrap_i_claim_hdr.
PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_rap_claim_hdr IMPLEMENTATION.
ENDCLASS.
